octopus:
  environments:
    - development
    - production
  development:
    shards:
      white:
        adapter: postgresql
        encoding: unicode
        database: white
        username: soldo        
      yellow:
        adapter: postgresql
        encoding: unicode
        database: yellow
        username: soldo        
      black:
        adapter: postgresql
        encoding: unicode
        database: black
        username: soldo        
      amber:
        adapter: postgresql
        encoding: unicode
        database: amber
        username: soldo        
      gold:
        adapter: postgresql
        encoding: unicode
        database: gold
        username: soldo        
      silver:
        adapter: postgresql
        encoding: unicode
        database: silver
        username: soldo        
      red:
        adapter: postgresql
        encoding: unicode
        database: red
        username: soldo        
      blue:
        adapter: postgresql
        encoding: unicode
        database: blue
        username: soldo        
  production:
    shards:
      white:
        adapter: postgresql
        database: dj21lsmiewecscn
        username: uf3ljol7ufl6wji
        password: p7fz8kjndmo8y4ia3omwk8mre3
        host: ec2-50-19-122-152.compute-1.amazonaws.com
      yellow:
        adapter: postgresql
        database: dc37wq7vnsskr83
        username: uy2nwf64mvc59tm
        password: pa93p1b6acd4fcrcmdbt5qbxox
        host: ec2-50-19-122-155.compute-1.amazonaws.com
      amber:
        adapter: postgresql
        database: dj21lsmiewecscn
        username: uf3ljol7ufl6wji
        password: p7fz8kjndmo8y4ia3omwk8mre3
        host: ec2-50-19-100-112.compute-1.amazonaws.com
      black:
        adapter: postgresql
        database: dc37wq7vnsskr83
        username: uy2nwf64mvc59tm
        password: pa93p1b6acd4fcrcmdbt5qbxox
        host: ec2-50-19-100-248.compute-1.amazonaws.com